# Generated by Django 4.2.1 on 2024-01-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostanaapp', '0002_deviceinfo_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField(choices=[(1, '1 Din'), (2, '2 Din'), (3, '3 Din')], default=1)),
                ('price_in_points', models.PositiveIntegerField()),
            ],
        ),
    ]
